# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'query#34' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for query#34
  pod 'AWSMobileClient'
  pod 'AWSAuthUI'
  pod 'AWSUserPoolsSignIn'
  pod 'AWSS3'
  pod 'AWSDynamoDB'
  pod 'AWSAppSync'
  pod 'Amplify'
end


