# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SPStorkController#73' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SPStorkController#73
  pod 'SPStorkController'

end
